# Generated by 'django-admin startproject' using Django 6.0.3.
# Settings Topic: https://docs.djangoproject.com/en/6.0/topics/settings/
# Settings Ref: https://docs.djangoproject.com/en/6.0/ref/settings/

import environ
from pathlib import Path

# environ for .env
env = environ.Env(
    DEBUG=(bool, False)  # Sets a default
)
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(BASE_DIR / '.env')

# varaibles 
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',
    'blog',
    'hub',
    'storages',
    'django_cleanup.apps.CleanupConfig'
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database: https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': env.db(),
}

STORAGES = {
    # ── Static files (unchanged — served from disk / whitenoise in prod) ─────
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
 
    # Main Storage: Supabase S3 (portfolio public assets) ────────────────
    # Use this explicitly when saving project screenshots, the avatar, CV, etc.
    # e.g.:  from django.core.files.storage import storages
    #        supabase_storage = storages["supabase"]
    "supabase": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key":        env('SUPABASE_ACCESS_KEY'),
            "secret_key":        env('SUPABASE_SECRET_KEY'),
            "bucket_name":       env('SUPABASE_BUCKET_NAME'),
            "endpoint_url":      env('SUPABASE_STORAGE_URL'),
            "region_name":       env('SUPABASE_REGION', default='ap-south-1'),
            # Supabase public bucket → no auth on read
            "default_acl":       "public-read",
            "querystring_auth":  False,
            "signature_version": "s3v4",
        },
    },

    # To be Implemented
    # Image Storage: CLOUD R2 (Blog related assets)
    # NOT used directly, (we generate presigned URLs ourselves)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key":        env('R2_ACCESS_KEY_ID'),
            "secret_key":        env('R2_SECRET_ACCESS_KEY'),
            "bucket_name":       env('R2_BUCKET_NAME'),
            "endpoint_url":      env('R2_ENDPOINT_URL'),
            # R2 has no region concept but boto3 requires something:
            "region_name":       "auto",
            # Don't expose the bucket in the URL — we use presigned URLs:
            "custom_domain":     None,
            "default_acl":       None,   # R2 ignores ACL; set to None
            "querystring_auth":  True,   # presigned URLs
            "signature_version": "s3v4",
        },
    },
}

# Redis Cache (Temporaily Off)
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": env('REDIS_URL', default='redis://localhost:6379/0'),
#     }
# }

# Password validation: https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization: https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images): https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # NEW: serve our CSS

# Auth settings for barebones login (name/password only)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'
