# Generated by Django 6.0.3 on 2026-05-03 00:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Title')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('image_1', models.ImageField(blank=True, null=True, storage=blog.models.BlogStorage(), upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, storage=blog.models.BlogStorage(), upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, storage=blog.models.BlogStorage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-created_at', '-id'],
            },
        ),
    ]
