# Generated by Django 6.0.3 on 2026-03-29 19:35

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_r2', models.FileField(blank=True, null=True, storage=album.models.R2Storage(), upload_to='photos/')),
                ('img_s3', models.FileField(blank=True, null=True, storage=album.models.SupabaseStorage(), upload_to='thumbs/')),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
