# Generated by Django 6.0.3 on 2026-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('brief_desc', models.TextField()),
                ('tech_stack', models.TextField(help_text='Comma-separated, e.g. Django, Supabase, Docker')),
                ('screenshot_url', models.URLField(blank=True, help_text='Public URL from Supabase Storage S3 bucket', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
