# Generated by Django 6.0.3 on 2026-03-24 18:50

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshot_url',
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_1',
            field=models.ImageField(null=True, storage=portfolio.models.PortfolioScreenshotStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_2',
            field=models.ImageField(blank=True, null=True, storage=portfolio.models.PortfolioScreenshotStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_3',
            field=models.ImageField(blank=True, null=True, storage=portfolio.models.PortfolioScreenshotStorage(), upload_to=''),
        ),
    ]
