# Generated by Django 6.0.3 on 2026-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_screenshot_url_project_screenshot_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='brief_desc',
        ),
        migrations.AddField(
            model_name='project',
            name='brief',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
