# Generated by Django 6.0.3 on 2026-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_brief_desc_project_brief_project_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
