# Generated by Django 6.0.3 on 2026-03-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_role_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Point Form, 2-3 strong points', null=True, verbose_name='Challenges & Solutions'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Point Form, 4-7 strong points', null=True, verbose_name='Features & Contributions'),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons',
            field=models.TextField(help_text='Personal Thoughts Paragrpah.', null=True, verbose_name='What I learned'),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief',
            field=models.CharField(help_text='for project_list page, brief intro', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, help_text='What it does, Why it exists & Value', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Solo, Backend, Group Lead etc', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(help_text='Live, Ongoing, Delayed, Completed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.TextField(help_text='Comma-separated, etc: Frontend: Backend: APIs: Databases: '),
        ),
    ]
