# Generated by Django 6.0.3 on 2026-03-26 16:32

import hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Game Title')),
                ('year', models.IntegerField(verbose_name='Release Year')),
                ('pity_num_std', models.IntegerField(help_text='e.g. 40', verbose_name='Std Soft Pity')),
                ('pity_max_std', models.IntegerField(help_text='e.g. 90', verbose_name='Std Hard Pity')),
                ('pity_num_lim', models.IntegerField(help_text='e.g. 40', verbose_name='Limited Soft Pity')),
                ('pity_max_lim', models.IntegerField(help_text='e.g. 90', verbose_name='Limited Hard Pity')),
                ('pity_num_wep', models.IntegerField(help_text='e.g. 30', verbose_name='Weapon Soft Pity')),
                ('pity_max_wep', models.IntegerField(help_text='e.g. 90', verbose_name='Weapon Hard Pity')),
                ('guaranteed', models.BooleanField(help_text='50/50 guarantee system?', verbose_name='Has Guarantee')),
                ('banner', models.ImageField(null=True, storage=hub.models.TrackerBannerStorage(), upload_to='', verbose_name='Banner Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
