# Generated by Django 6.0.3 on 2026-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gacha',
            name='guaranteed',
        ),
        migrations.AddField(
            model_name='gacha',
            name='gr_lim',
            field=models.BooleanField(default=False, verbose_name='Guaranteed?'),
            preserve_default=False,
        ),
    ]
