# Generated by Django 6.0.3 on 2026-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_gacha_guaranteed_gacha_gr_lim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gacha',
            name='gr_lim',
            field=models.BooleanField(verbose_name='Weapon Guaranteed?'),
        ),
    ]
