# Generated by Django 6.0.3 on 2026-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_gacha_gr_lim'),
    ]

    operations = [
        migrations.AddField(
            model_name='gacha',
            name='gr_wep',
            field=models.BooleanField(default=False, verbose_name='Weapon Guaranteed?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gacha',
            name='gr_lim',
            field=models.BooleanField(verbose_name='Limited Guaranteed?'),
        ),
    ]
